FROM node:16.20.2 as build-stage

WORKDIR /app

# 复制 package.json 和 package-lock.json
COPY package*.json ./
RUN mkdir -p node_modules && chown -R node:node .

USER node

# 安装依赖，确保包含 axios
RUN npm install --no-optional --legacy-peer-deps && \
    npm install axios@latest element-plus@latest

# 以 node 用户身份复制其他文件
COPY --chown=node:node . .

RUN npm run build

FROM nginx:1.24.0 as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"] 